:navtitle: Spring Ahead of Time
= Spring Ahead of Time

link:https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.introducing-graalvm-native-images.understanding-aot-processing[Spring AOT processing,window=_blank,role=external] is part of the process to create a native binary from a Spring (Boot) application. This extension will help in adding a lot of hints which are needed for Axon Framework. Please note this extension can only be used with Spring Boot 3, as such it requires at least Java 17.

Besides the extension, it might be necessary to make more changes to successfully compile and run an application as a native image. For example, when a message isn't used in a handler. This is quite common when the application is split, and the application sending certain messages is not the same as the application handling the messages. In those cases these messages need to be added to the link:https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/ImportRuntimeHints.html[`ImportRuntimeHints`,window=_blank,role=external] annotation. Otherwise, these messages can't be deserialized, leading to errors at runtime.

If something is not working or only works with additional hints, and it's Axon-specific, please let us know either at link:https://github.com/AxonFramework/extension-spring-aot/issues[GitHub,window=_blank,role=external] or link:https://discuss.axoniq.io/c/axonframework/[Discuss,window=_blank,role=external].